package com.gopawpaw.erp.hibernate.g;

/**
 * GlCtrl entity. @author MyEclipse Persistence Tools
 */
public class GlCtrl extends AbstractGlCtrl implements java.io.Serializable {

	// Constructors

	/** default constructor */
	public GlCtrl() {
	}

	/** minimal constructor */
	public GlCtrl(String glExRndAcct, String glExRndCc, String glExRatetype,
			String glUgainAcct, String glUgainCc, String glUlossAcct,
			String glUlossCc, String glRgainAcct, String glRgainCc,
			String glRlossAcct, String glRlossCc, String glFsdefAcct,
			String glFsdefSub, String glFsdefCc, String glFsaccrAcct,
			String glFsaccrSub, String glFsaccrCc, String glTimezone,
			Double oidGlCtrl) {
		super(glExRndAcct, glExRndCc, glExRatetype, glUgainAcct, glUgainCc,
				glUlossAcct, glUlossCc, glRgainAcct, glRgainCc, glRlossAcct,
				glRlossCc, glFsdefAcct, glFsdefSub, glFsdefCc, glFsaccrAcct,
				glFsaccrSub, glFsaccrCc, glTimezone, oidGlCtrl);
	}

	/** full constructor */
	public GlCtrl(String glArAcct, String glArCc, String glDiscAcct,
			String glQadc01, String glQadc03, String glQadc05,
			String glTermAcct, String glFinAcct, String glRtnsAcct,
			String glCsAcct, String glDiscCc, String glQadc02, String glQadc04,
			String glQadc06, String glTax1Cc, String glTax2Cc, String glTax3Cc,
			String glTermCc, String glFinCc, String glRtnsCc, String glCsCc,
			String glTax1Acct, String glTax2Acct, String glTax3Acct,
			String glSlsAcct, String glSlsCc, String glApAcct, String glApCc,
			String glPurAcct, String glPurCc, String glInvAcct, String glInvCc,
			String glDscrAcct, String glDscrCc, String glWipAcct,
			String glWipCc, String glCogAcct, String glCogCc,
			String glScrpAcct, String glScrpCc, String glApdsAcct,
			String glApdsCc, Boolean glVerify, String glPpvAcct,
			String glPpvCc, String glRcptAcct, String glRcptCc,
			String glBdnAcct, String glBdnCc, String glLbrAcct, String glLbrCc,
			String glLvarAcct, String glLvarCc, String glOtAcct, String glOtCc,
			String glCopAcct, String glCopCc, String glWvarAcct,
			String glWvarCc, String glBaseCurr, String glSymbol,
			String glUserAcct, String glUserCc, String glEntity,
			Integer glQad01, String glUser1, String glUser2, Integer glIndex1,
			Boolean glVat, Integer glExRound, Boolean glCan, String glCchgAcct,
			String glCchgCc, String glXferAcct, String glXferCc,
			String glCmtlAcct, String glCmtlCc, String glClbrAcct,
			String glClbrCc, String glCbdnAcct, String glCbdnCc,
			String glCovhAcct, String glCovhCc, String glCsubAcct,
			String glCsubCc, String glApvrAcct, String glApvrCc,
			String glApvuAcct, String glApvuCc, String glBvarAcct,
			String glBvarCc, String glLvrrAcct, String glLvrrCc,
			String glBvrrAcct, String glBvrrCc, String glOvhAcct,
			String glOvhCc, Boolean glQadl01, Integer glSubLen,
			String glMvarAcct, String glMvarCc, String glMvrrAcct,
			String glMvrrCc, String glSvarAcct, String glSvarCc,
			String glSvrrAcct, String glSvrrCc, String glQadc07,
			String glQadc08, String glFlrAcct, String glFlrCc,
			String glEslsAcct, String glEslsCc, String glTaxType,
			String glFrtappAcct, String glFrtappCc, String glFrtaccAcct,
			String glFrtaccCc, String glBkVal, String glApvrxAcct,
			String glApvrxCc, String glApvuxAcct, String glApvuxCc,
			String glRcptxAcct, String glRcptxCc, String glCrtermsAcct,
			String glCrtermsCc, String glLateAcct, String glLateCc,
			String glXvarAcct, String glXvarCc, String glRndMthd,
			String glLang, String glFslbrAcct, String glFslbrCc,
			String glFsbdnAcct, String glFsbdnCc, String glFsexpAcct,
			String glFsexpCc, String glFsexdAcct, String glFsexdCc,
			String glFsrcInvAcct, String glFsrcInvCc, String glFscmInvAcct,
			String glFscmInvCc, String glRmarAcct, String glRmarCc,
			String glExRndAcct, String glExRndCc, String glExRatetype,
			String glUgainAcct, String glUgainCc, String glUlossAcct,
			String glUlossCc, String glRgainAcct, String glRgainCc,
			String glRlossAcct, String glRlossCc, String glApdsSub,
			String glApvrxSub, String glApvrSub, String glApvuxSub,
			String glApvuSub, String glApSub, String glArSub, String glBdnSub,
			String glBvarSub, String glBvrrSub, String glCbdnSub,
			String glCchgSub, String glClbrSub, String glCmtlSub,
			String glCogSub, String glCopSub, String glCovhSub,
			String glCrtermsSub, String glCsubSub, String glCsSub,
			String glDiscSub, String glDscrSub, String glExRndSub,
			String glFinSub, String glFlrSub, String glFrtaccSub,
			String glFrtappSub, String glFsbdnSub, String glFscmInvSub,
			String glFsexdSub, String glFsexpSub, String glFslbrSub,
			String glFsrcInvSub, String glInvSub, String glLateSub,
			String glLbrSub, String glLvarSub, String glLvrrSub,
			String glMvarSub, String glMvrrSub, String glOtSub,
			String glOvhSub, String glPpvSub, String glPurSub,
			String glRcptxSub, String glRcptSub, String glRgainSub,
			String glRlossSub, String glRmarSub, String glRtnsSub,
			String glScrpSub, String glSlsSub, String glSvarSub,
			String glSvrrSub, String glTermSub, String glTxapAcct,
			String glTxapSub, String glTxapCc, String glTxaprAcct,
			String glTxaprSub, String glTxaprCc, String glTxarAcct,
			String glTxarSub, String glTxarCc, String glTxaraAcct,
			String glTxaraSub, String glTxaraCc, String glUgainSub,
			String glUlossSub, String glUserSub, String glWipSub,
			String glWvarSub, String glXferSub, String glXvarSub,
			String glFsdefAcct, String glFsdefSub, String glFsdefCc,
			String glFsaccrAcct, String glFsaccrSub, String glFsaccrCc,
			String glTimezone, Double oidGlCtrl) {
		super(glArAcct, glArCc, glDiscAcct, glQadc01, glQadc03, glQadc05,
				glTermAcct, glFinAcct, glRtnsAcct, glCsAcct, glDiscCc,
				glQadc02, glQadc04, glQadc06, glTax1Cc, glTax2Cc, glTax3Cc,
				glTermCc, glFinCc, glRtnsCc, glCsCc, glTax1Acct, glTax2Acct,
				glTax3Acct, glSlsAcct, glSlsCc, glApAcct, glApCc, glPurAcct,
				glPurCc, glInvAcct, glInvCc, glDscrAcct, glDscrCc, glWipAcct,
				glWipCc, glCogAcct, glCogCc, glScrpAcct, glScrpCc, glApdsAcct,
				glApdsCc, glVerify, glPpvAcct, glPpvCc, glRcptAcct, glRcptCc,
				glBdnAcct, glBdnCc, glLbrAcct, glLbrCc, glLvarAcct, glLvarCc,
				glOtAcct, glOtCc, glCopAcct, glCopCc, glWvarAcct, glWvarCc,
				glBaseCurr, glSymbol, glUserAcct, glUserCc, glEntity, glQad01,
				glUser1, glUser2, glIndex1, glVat, glExRound, glCan,
				glCchgAcct, glCchgCc, glXferAcct, glXferCc, glCmtlAcct,
				glCmtlCc, glClbrAcct, glClbrCc, glCbdnAcct, glCbdnCc,
				glCovhAcct, glCovhCc, glCsubAcct, glCsubCc, glApvrAcct,
				glApvrCc, glApvuAcct, glApvuCc, glBvarAcct, glBvarCc,
				glLvrrAcct, glLvrrCc, glBvrrAcct, glBvrrCc, glOvhAcct, glOvhCc,
				glQadl01, glSubLen, glMvarAcct, glMvarCc, glMvrrAcct, glMvrrCc,
				glSvarAcct, glSvarCc, glSvrrAcct, glSvrrCc, glQadc07, glQadc08,
				glFlrAcct, glFlrCc, glEslsAcct, glEslsCc, glTaxType,
				glFrtappAcct, glFrtappCc, glFrtaccAcct, glFrtaccCc, glBkVal,
				glApvrxAcct, glApvrxCc, glApvuxAcct, glApvuxCc, glRcptxAcct,
				glRcptxCc, glCrtermsAcct, glCrtermsCc, glLateAcct, glLateCc,
				glXvarAcct, glXvarCc, glRndMthd, glLang, glFslbrAcct,
				glFslbrCc, glFsbdnAcct, glFsbdnCc, glFsexpAcct, glFsexpCc,
				glFsexdAcct, glFsexdCc, glFsrcInvAcct, glFsrcInvCc,
				glFscmInvAcct, glFscmInvCc, glRmarAcct, glRmarCc, glExRndAcct,
				glExRndCc, glExRatetype, glUgainAcct, glUgainCc, glUlossAcct,
				glUlossCc, glRgainAcct, glRgainCc, glRlossAcct, glRlossCc,
				glApdsSub, glApvrxSub, glApvrSub, glApvuxSub, glApvuSub,
				glApSub, glArSub, glBdnSub, glBvarSub, glBvrrSub, glCbdnSub,
				glCchgSub, glClbrSub, glCmtlSub, glCogSub, glCopSub, glCovhSub,
				glCrtermsSub, glCsubSub, glCsSub, glDiscSub, glDscrSub,
				glExRndSub, glFinSub, glFlrSub, glFrtaccSub, glFrtappSub,
				glFsbdnSub, glFscmInvSub, glFsexdSub, glFsexpSub, glFslbrSub,
				glFsrcInvSub, glInvSub, glLateSub, glLbrSub, glLvarSub,
				glLvrrSub, glMvarSub, glMvrrSub, glOtSub, glOvhSub, glPpvSub,
				glPurSub, glRcptxSub, glRcptSub, glRgainSub, glRlossSub,
				glRmarSub, glRtnsSub, glScrpSub, glSlsSub, glSvarSub,
				glSvrrSub, glTermSub, glTxapAcct, glTxapSub, glTxapCc,
				glTxaprAcct, glTxaprSub, glTxaprCc, glTxarAcct, glTxarSub,
				glTxarCc, glTxaraAcct, glTxaraSub, glTxaraCc, glUgainSub,
				glUlossSub, glUserSub, glWipSub, glWvarSub, glXferSub,
				glXvarSub, glFsdefAcct, glFsdefSub, glFsdefCc, glFsaccrAcct,
				glFsaccrSub, glFsaccrCc, glTimezone, oidGlCtrl);
	}

}
